// <auto-generated />
using System;
using LoteriaFacil.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoteriaFacil.Infra.Data.Migrations
{
    [DbContext(typeof(LoteriaFacilContext))]
    [Migration("20190919195243_Remocao_Tabelas")]
    partial class Remocao_Tabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoteriaFacil.Domain.Models.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Calcular_Dezenas_Sem_Pontuacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Checar_Jogo_Online")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Enviar_Email_Automaticamente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Enviar_Email_Manualmente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Valor_Minimo_Para_Envio_Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("LoteriaFacil.Domain.Models.Lottery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Concurse");

                    b.Property<DateTime>("DtConcurse");

                    b.Property<DateTime>("DtNextConcurse");

                    b.Property<string>("Game");

                    b.Property<int>("Hit11");

                    b.Property<int>("Hit12");

                    b.Property<int>("Hit13");

                    b.Property<int>("Hit14");

                    b.Property<int>("Hit15");

                    b.Property<decimal>("Shared11");

                    b.Property<decimal>("Shared12");

                    b.Property<decimal>("Shared13");

                    b.Property<decimal>("Shared14");

                    b.Property<decimal>("Shared15");

                    b.Property<Guid?>("TypeLotteryId");

                    b.HasKey("Id");

                    b.HasIndex("TypeLotteryId");

                    b.ToTable("Lottery");
                });

            modelBuilder.Entity("LoteriaFacil.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DtRegister");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LoteriaFacil.Domain.Models.TypeLottery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Bet_Min");

                    b.Property<int>("Hit_Max");

                    b.Property<int>("Hit_Min");

                    b.Property<string>("Name");

                    b.Property<int>("Tens_Min");

                    b.HasKey("Id");

                    b.ToTable("TypeLottery");
                });

            modelBuilder.Entity("LoteriaFacil.Domain.Models.Lottery", b =>
                {
                    b.HasOne("LoteriaFacil.Domain.Models.TypeLottery", "TypeLottery")
                        .WithMany()
                        .HasForeignKey("TypeLotteryId");
                });
#pragma warning restore 612, 618
        }
    }
}
